# Generated by Django 4.1.4 on 2022-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_item_id_cart_item_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default='Item', max_length=150),
            preserve_default=False,
        ),
    ]
